### ISSUE TITLE
Stuck at processing

### ISSUE THREAD

**Issue by skirge** [codedx/codepulse#18]
I've uploaded a jar file, but after clicking OK Codepulse stucks at 'Processing' message or shows 'Processing data failed' message. 
There is no log file or debug message in terminal.

[activemq-all-5.16.0-SNAPSHOT.zip](https://github.com/codedx/codepulse/files/1603105/activemq-all-5.16.0-SNAPSHOT.zip)

**Comment by stevesalas** [comment]
Hello, thanks for reporting this issue. The dev/java-8 branch now includes a change that should resolve this bug. There's a new pull request to incorporate changes into the main branch, and we plan on creating a new release following acceptance of the changes.

**Comment by skirge** [comment]
I've tried dev/java-8 branch but got this when run with agent:

```
MAVEN_OPTS="-javaagent:<redacted>/codepulse/bytefrog/agent/target/scala-2.10/bytefrog-tracer.jar=localhost:8765" mvn exec:java
```


```
java.lang.IllegalArgumentException: INVOKESPECIAL/STATIC on interfaces require ASM 5
	at com.secdec.bytefrog.asm.MethodVisitor.visitMethodInsn(Unknown Source)
	at com.secdec.bytefrog.asm.commons.AdviceAdapter.visitMethodInsn(Unknown Source)
	at com.secdec.bytefrog.asm.ClassReader.a(Unknown Source)
	at com.secdec.bytefrog.asm.ClassReader.b(Unknown Source)
	at com.secdec.bytefrog.asm.ClassReader.accept(Unknown Source)
	at com.secdec.bytefrog.asm.ClassReader.accept(Unknown Source)
	at com.secdec.bytefrog.agent.bytefrog.Instrumentor.instrument(Instrumentor.java:44)
	at com.secdec.bytefrog.agent.bytefrog.Instrumentor.instrument(Instrumentor.java:58)
	at com.secdec.bytefrog.agent.trace.TraceClassFileTransformer.transform(TraceClassFileTransformer.java:161)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at <redacted>.lambda$bindAsync$4(<redacted>:666)
```

**Comment by stevesalas** [comment]
Thanks for the feedback. The dev/java-8 branch now includes a bytefrog update that also references ASM5.

**Comment by skirge** [comment]
I've tested dev/java-8 and it works fine, thanks.
